### ISSUE TITLE
Render markdown

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/modular-file-renderer#142]
We should have a markdown renderer. Preferably [CommonMark](https://github.com/jgm/commonmark.js) to start.

**Comment by TomBaxter** [comment]
I put in a pull request for markdown support, but it does not utilize a CommonMark library. I did a little research and was unable to find an active python library project. There is an actively supported Java Script library however. I am new to Java Script but I'll investigate using that library.

**Comment by brianjgeiger** [comment]
We are using markdown-js for wiki things on the osf, so that would be the ideal one to use.

**Comment by TomBaxter** [comment]
Ok, thanks, I'll look at that.

**Comment by mfraezz** [comment]
Closed via #198 and #206
