### ISSUE TITLE
MFR loading spinner lower resolution than other OSF spinners

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/modular-file-renderer#182]
I reported this on the 0.46 trello board.

## Steps

1. Log into osf.io.
2. Navigate to one of your projects.
3. Click on a file to render it on the file detail page.
4. Notice the spinner in the file tree and the spinner in the renderer as the page is loading.

## Expected behavior

I expect the spinners to be the same resolution.

## Actual behavior

The spinner in the MFR is lower resolution than other OSF spinners, including the one on the same page in the file tree on the left.

## Screenshots

**File tree spinner**

![files_grid_high_resolution_spinner](https://cloud.githubusercontent.com/assets/7093086/9333047/c9930f90-4595-11e5-94a3-5c89da77e2df.png)

**MFR spinner**

![mfr_low_resolution_spinner](https://cloud.githubusercontent.com/assets/7093086/9333039/c45ce7da-4595-11e5-9a01-052ca375c22d.png)

**Comment by mfraezz** [comment]
The OSF's [spinner](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/static/img/logo_spin.png) should be the same file as the MFR's [spinner](https://github.com/CenterForOpenScience/modular-file-renderer/blob/develop/mfr/server/static/images/loading.png), it looks like the latter is just being resized to fit a larger container. Replacing it with a [higher res version](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/static/img/circle_logo.png) should fix this.

**Comment by lbanner** [comment]
@NatashaRichter -- should this be transferred to OSF issues?

**Comment by mfraezz** [comment]
MFR delivers the spinner file when it's rendering, so it really belongs here, but it might receive more attention there. That being said, I can fix it in about 30 seconds if the above is the desired solution. A likely side effect would be that the spinner could be slightly larger, unless we're giving it an exact size.

**Comment by NatashaRichter** [comment]
@lbanner @mfraezz Whatever you both think is best. Caner had recommended I put it up here, but I can move it. All the OSF spinners are the same size now, except for this MFR spinner, which is larger than the others. If possible, we'd want it to be the exact size as the other spinners.
