### ISSUE TITLE
Internet Explorer's MFR lacks loading spinner

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/modular-file-renderer#183]
**IE 11**
Notice that there is only white space where there should be a loading spinner for the MFR.

![screen shot 2015-08-18 at 1 13 03 pm](https://cloud.githubusercontent.com/assets/8591162/9337042/e2bff5ea-45aa-11e5-846a-1c383fbb0f2e.png)

**Correct appearance**
![screen shot 2015-08-18 at 1 13 45 pm](https://cloud.githubusercontent.com/assets/8591162/9337076/086180f2-45ab-11e5-876f-872594d914ae.png)

**Comment by mfraezz** [comment]
There's a related issue with Firefox (and FDE), where the spinner is displayed but does not spin. Opacity does fluctuate.

It seems strange to me that, with the desire to keep the MFR as a separate service, we're handling this  on the MFR side. The COS/OSF logo appears nowhere else in the MFR, and it would be simpler for the OSF to just display the same spinner that's everywhere else on the site and replace it when the rendering completes than to have the MFR try (unsuccessfully) to deliver a different but equivalent one (In addition to this issue, there's also https://github.com/CenterForOpenScience/modular-file-renderer/issues/182). Pinging @sloria and @icereval about this

**Comment by GaryKriebel** [comment]
I think @mfraezz makes a good point about keeping the service separate and have the OSF display a spinner/loader that conforms to the decided upon style.

**Comment by JeffSpies** [comment]
Three issues here?

1) I agree with @mfraezz on his proposed solution. That would be a bit better.
2) The spinner needs to spin on all browsers.
3) The spinner needs to show up on all browses.

@sloria, @icereval disregard. 

@erinmayhood, can these be processed into Jira?

**Comment by erinmayhood** [comment]
@JeffSpies yes, I will get this into Jira.

**Comment by felliott** [comment]
The COS spinner was debranded from MFR with commit 3c818cdf55cfc9b553f351661f6e3ad10327d2ae.  Marking as closed.
