### ISSUE TITLE
.rst files are being rendered by CodePygmentsRenderer not RstRenderer

### ISSUE THREAD

**Issue by TomBaxter** [CenterForOpenScience/modular-file-renderer#200]
If RstRenderer is ready to go I can put in a pull request. All that needs updating is ../modular-file-renderer/setup.py

**Comment by mfraezz** [comment]
I don't know of any reason why we're not using the RstRenderer. Go ahead and test it out locally, if it looks good and doesn't allow for arbitrary html injection, please submit a PR.

**Comment by mfraezz** [comment]
Closed via #201 and #206
