### ISSUE TITLE
The example code in the documentation doesn't work for me: No module named 'mfr_image'

### ISSUE THREAD

**Issue by rija** [CenterForOpenScience/modular-file-renderer#228]
Hi,

I've built the doc in an up-to-date checkout in order to get the most up-to-date documentation. 
In the Examples section, there is a Flask code sample that is not working for me. 

While running the Flask web app in my MFR virtualenv from its own directory, I got the following error: 

```bash
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    import mfr_image
ImportError: No module named 'mfr_image'

```

the mfr module has previously been installed successfully with `invoke install -d`  in the virtualenv.

Do I have to do something special to install that extension (mfr-image) in my virtualenv's site-package?

**Comment by felliott** [comment]
Hey @rija,

Yikes! I assume you're talking about https://github.com/CenterForOpenScience/modular-file-renderer/blob/develop/docs/examples.rst, correct?  I haven't looked at that doc before, but I think it's tremendously out-of-date.  The actual exporting and rendering functions are importable and can be used within a Flask app. e.g.

```python
import mfr.extensions.image as mfr_image
foo = mfr_image.export.ImageExporter('/tmp/input.jpg', '/tmp/output.png', 'png')
```

I don't think the web handler will work inside Flask.  The MFR web handler is now a standalone tornado app.  Only the OSF auth/metadata provider is well-tested, but I would be interested in either improving the http provider or merging a dummy provider, if you're willing to run it.  What's your use case?

Cheers,
Fitz

**Comment by rija** [comment]
I fixed the issue by replacing the line 

```bash
import mfr_image
```

with 

```bash
from mfr.extensions import image
```

**Comment by rija** [comment]
Hi Fitz, 

thanks for your answer. Got the import working. but got a new error:

```bash
Traceback (most recent call last):
  File "app.py", line 40, in <module>
    main()
  File "app.py", line 35, in main
    'HANDLERS': [mfr_image.Handler]
AttributeError: module 'mfr.extensions.image' has no attribute 'Handler'
```

I'm not particularly attached to Flask. I was just playing with the examples to understand how MFR works. 

my use case is: 

I want to run a standalone web app that would render preview for files hosted on an FTP server.

The render urls will be used on a php web app to offer preview functionality to visitors before they download the files. 

There doesn't seem to be an FTP provider. but I guess the HTTP provider would understand ftp:// type of urls?

**Comment by felliott** [comment]
Hey @rija,

It sounds like your best bet is just to run MFR as a standalone app.  Start it with `invoke server` and it will start listening for connections on `localhost:7778`.    Rendering is handled by requests to `http://localhost:7778/render?url=<percent-encoded-url>`.  Exporting is handled by requests like `http://localhost:7778/export?url=<percent-encoded-url>&format=<file-format>`.

I don't think the http provider will handle ftp requests, because I don't think the underlying library (aiohttp) handles ftp. If you wanted to create an ftp handler, it would probably look very similar to the http provider but would use an async ftp library like [aioftp](https://pypi.python.org/pypi/aioftp/0.6.1) instead.

Cheers,
Fitz

**Comment by rija** [comment]
Hi @felliott,

Thank you for your comprehensive answer.

Creating a new aioftp-based FTP provider that parallel the http provider sound reasonable approach to me.

I have a few follow up questions:

* May I create a  new ticket specifically to track that work rather than piggy-back on this issue?

* also I would like some advice regarding the metadata endpoint of the provider api: The files that we want to preview are genomics research related (e.g: FASTA) so it's unlikely that python mime types could guess them. Can we add an additional mime.types file in the git directory structure of the new provider to be read with `mimetypes.read_mime_types` so that we have the correct metadata for the files we need to handle?

* the files we need to work with are often very large (> GB). with Async and streaming approach it should be ok, but are there are any other considerations I should take into account with respect to MFR resilience ?

Warmly,
Rija

**Comment by felliott** [comment]
Hey @rija!

1. Sure, go ahead and create a new ticket!
2. That seems like a reasonable approach.  I'd have to see it to be sure, but that sounds right.
3. If these files are so large, how does rendering them work?  Dumping a multi-GB FASTA file to the users browser will probably lock up / slow the users browser.  What format are you trying to render these as?

Cheers,
@felliott

**Comment by felliott** [comment]
Addendum: exporting / rendering sometimes requires a local cache of the file to work.  An example is that we use the `unoconv` package to convert document files (.docx, etc.) to pdf, which are then rendered with the pdf renderer.  If you're downloading and caching lots of large files, you'll need to keep an eye on your disk space on your MFR server.

**Comment by rija** [comment]
Hi @felliott 

thank you for your reply and for the advices.


(a) For tabular based format like TSV,  VCF, GFF, HDF5  we aim to show the first 50 rows of the document when rendering the preview as a table.
I'm hoping I can use the Tabular extension for that. looking at the settings, I can see:

MAX_SIZE = int(config.get('MAX_SIZE', 10000))
TABLE_WIDTH = int(config.get('TABLE_WIDTH', 700))
TABLE_HEIGHT = int(config.get('TABLE_HEIGHT', 600))

which seems to indicate it's possible. 
I will need to extend the pandas tools lib to handle our formats (pandas tools support them already)

(b) For the text-based formats like FASTQ, FASTA, we aim to show the first 50 lines of the document when rendering the preview as text.
I was hoping I can use unoconv extension for that, but it may not be suitable as i need to have the document truncated appropriately before I pass it on to unoconv for conversion to HTML
And because there are just text formats, it seems It’s better for me to create a dedicated extension for bio formats. 

(c) For image based formats like PNG, GIF, TIFF, we show a cropped version of the image.
I’m hoping I can use the image extension for that.


Because the files are very larges, and because we will also enable ability to download the files, I need the FTP provider to keep the files locally, so yes, I need to manage disk space on the tornado server. 

Cheers
Rija

**Comment by felliott** [comment]
Hey @rija,

a.) Displaying just a portion of a large file would be a really useful feature, but it's not one we currently have.  So far we've been dealing with it by simply refusing to render files bigger than a certain size (text files > 200kb, coming soon: tabular files > ??Mb).  But showing only the first X rows, lines, bytes would be a good way to approach this.  I'll talk to our Product team here at COS and see if there's internal interest in developing this.

b.) You might look at the codepygments extension renderer, which is used to add render source code with syntax highlighting.

c.) The image extension will do scaling, but doesn't yet do cropping.  That would be an interesting feature.

MFR could be updated to support downloading, but you might look at MFR's sister project [WaterButler](https://github.com/centerforopenscience/waterbutler). WaterButler provides a common RESTful interface to a bunch of different storage providers like Dropbox, GoogleDrive, Amazon S3, etc.  It could be updated to add an async ftp provider.  The OSF auth provider in MFR already uses WB for all its file operations.

Cheers,
Fitz

**Comment by felliott** [comment]
Hey @rija,

I'm doing some New Year's cleaning of the issue/PR queues.  This issue has fragmented into a couple of different issues, so I'll address each, then close this issue.  If you'd like to pursue them, please open new issues.

First, from the previous comment:

a.) We're still interested in doing partial rendering, but don't have a lot of bandwidth to work on it ATM.  If this is a feature you'd really like, please email our help desk at contact@cos.io.  That helps us keep track of community-requested features and prioritize around them.

b.) We [added support](https://github.com/CenterForOpenScience/modular-file-renderer/commit/38e8a40e599e634170d9add6155afe17e8ff4f63#diff-2eeaed663bd0d25b7e608891384b7298R279) for `.fasta` files in v0.22.0.  We'll be updating our codepygments dependency in the next release (already in `develop`), so if that supports more formats we should be able to handle them, too.

c.)  We're still not yet planning on adding explicit cropping, but there is work ongoing (see #306) to add high-resolution dynamic zooming.

<The original issue> Wow, I'm embarrassed that I still haven't deleted the out-of-date docs!  I've created a ticket on our internal tracker to make sure it gets done.
