### ISSUE TITLE
Open XML SDK for JavaScript API

### ISSUE THREAD

**Issue by binoculars** [CenterForOpenScience/modular-file-renderer#23]
I came across this the other day: http://openxmldeveloper.org/wiki/w/wiki/overview-of-the-open-xml-sdk-for-javascript-api.aspx

Code available at: https://openxmlsdkjs.codeplex.com/

There's no UI to it, but that might be a good thing to build on top of it. It would be possible to edit documents, presentations, and spreadsheets. All of the rendering and/or editing could be done client-side. If you wanted to do read-only, we could build a node.js module.

**Comment by felliott** [comment]
I declare that this issue shall not survive into its fourth year!  The library was last updated in [November 2013](https://openxmlsdkjs.codeplex.com/), and I think editing OOXML documents is no longer part of MFR's mandate.  Marking this as closed.

(Observers: I work with @binoculars, he can pelt me with Diet Cokes if my decision was too hastily made.)

(Addendum: the official Microsoft Open XML SDK is [still being developed](https://github.com/OfficeDev/Open-XML-SDK), but it's .Net only)

**Comment by binoculars** [comment]
I should've been vote into and kicked out of public office by now! Taking a few minutes to reexamine my life.
