### ISSUE TITLE
problems with docx

### ISSUE THREAD

**Issue by sonnenschein123** [CenterForOpenScience/modular-file-renderer#263]
Hello, 
if I try to render a docx document with UNOCONV it always throw the message `mfr.core.exceptions.SubprocessError: 400, Unable to export the file in the requested format, please try again later.`. 
I solved this problem be adding the file extension to the `source_file_id`:
      `self.source_file_path = await self.local_cache_provider.validate_path(`
          `'/export/{}'.format(self.source_file_id) + self.metadata.ext`
      `)`

Has anyone else this problem, what do you do on osf.io to render docx files?

Best sonnenschein123

**Comment by felliott** [comment]
Hey @sonnenschein123,

Apologies for the delay.  The `develop` branch of MFR just had some code merged to help render docx files in development environments.  You'll need to be running the OSF using docker-compose [per these instructions](https://github.com/CenterForOpenScience/osf.io/blob/develop/README-docker-compose.md) and also bring up the `unoconv` container defined there (`docker-compose up -d unoconv`).  After that, .docx files should start to render in local MFR.

I have this running locally, so I'm marking this as closed.  If it doesn't work for you, please feel free to reopen!

Cheers,
@felliott
