### ISSUE TITLE
Render videos

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/modular-file-renderer#27]
Something like this might help: https://github.com/videojs/video.js

**Comment by felliott** [comment]
Closing this as part of New Year's triage.  The native `<video>` tag nowadays does a pretty good job of supporting mp4/webm/ogv and neither of the above libraries support avi out-of-the-box.

(Please don't ask about [Safari](https://github.com/CenterForOpenScience/waterbutler/pull/234), I beg you)

Cheers,
@felliott
