### ISSUE TITLE
Render HTML

### ISSUE THREAD

**Issue by rubenarslan** [CenterForOpenScience/modular-file-renderer#354]
Would it be possible to render HTML files in the file browser view without having to download them?

When I originally shared my rmarkdown output on the OSF, you still used to render HTML when clicking the download button. Now users have to download the files and view them locally. This extra step made me switch to Github pages.

But as far as I can tell, you could safely include files from your API via <iframe src="" sandbox="">
https://osf.io/5st8i/ They are also hosted on the files subdomain, so cookies aren't shared with the main osf.io. AFAICT this addresses reasonable worries about cross-site scripting (everything else might also happen when people download the HTML files).

Any reason not to do this? Currently, this encourages people to upload PDFs which are very lossy and not easily machine-readable. 

Moved from https://github.com/CenterForOpenScience/osf.io/issues/7482

The other reason why HTML rendering would be cool is that when people upload codebooks generated using my [R package](https://github.com/rubenarslan/codebook), the metadata would be indexable (e.g. by Google Dataset Search). This would allow users to supply their own metadata for their datasets – facilitating bottom-up metadata until the OSF implements full JSON-LD.

**Comment by felliott** [comment]
Hey @rubenarslan,

This is something we've investigated and decided that it's not currently feasible for us to attempt.  The cookies issue is still present as scripts loaded from files.osf.io would have access to (and could exfiltrate) the osf.io cookies.  We're also worried about the possibility of abusing other sites via hotlinking.  Yet another concern is the difficulty of resolving relative links in a manner that produces consistently satisfactory results.

When we looked at other providers that provide file hosting, we found that the only major storage provider that supports rendering html files was Dropbox.  That support is pretty rudimentary and doesn't handle css and script links very gracefully.  See also [this post](https://rawgit.com/) from rawgit.com, a CDN service that supported rendering files from Github.  We don't currently have the resource to support a comparable service like this for the OSF.

Cheers,
@felliott

**Comment by rubenarslan** [comment]
Hi @felliott. The precedent example for a static website hoster would be Github pages or Netlify? I.e., either use a subdomain domain (like app.netlify.com) for main app cookies or use a separate domain for hosting (like github.io).
While I can see there are obstacles to doing this in a _great_ way, rmarkdown reports (what most of my colleagues use) are self contained for that reason. So it seems there would be a good enough way.

I can't assess the problem of abuse well, but I would expect you get 99% of the problems with offering free, private, large file storage already...
