### ISSUE TITLE
Mapping possible render options

### ISSUE THREAD

**Issue by Ghalko** [CenterForOpenScience/modular-file-renderer#89]
Internal structure added to map possible options to render. This might need to be a list of format modules that contributors have written. This could also convert one format to another, for the user.

**Comment by felliott** [comment]
This already sort of happens in [setup.py](https://github.com/CenterForOpenScience/modular-file-renderer/blob/develop/setup.py), but we've made it more generally available as [static documentation](https://github.com/CenterForOpenScience/modular-file-renderer/blob/develop/supportedextensions.md) and as two new endpoints, `/renderers` and `/exporters`, which return JSON objects containing the extension-to-handler mappings.  Closing.
